### ISSUE TITLE
[BUG] How do we perform updates of statefulset? Blocks helm updates.

### ISSUE THREAD

**Issue by JaredDarling** [Ontotext-AD/graphdb-helm#146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Version

11.2.2

### Current Behavior

A company I am working at is evaluating Graphdb. Our infrastructure is k8s, so I thought I would take advantage of using your helm chart. A common activity is the need to modify the configuration of the server. We need to adjust storage sizes, add properties to the configmap so `graphdb.properties` is updated and a number of other configuration properties, however when I try to update the values in the helm chart, I get the following error:

Helm upgrade failed for release graphdb/graphdb-graphdb-helm with chart graphdb@11.2.2: cannot patch "graphdb-graphdb-helm" with kind StatefulSet: StatefulSet.apps "graphdb-graphdb-helm" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden

This won't due. It results in having to delete the whole helm chart and re-install it new in order to perform updates. Deleting the helm chart causes all of the data to be lost and the server has to be restored from backup. Is that really the intended operations procedure?

Please advise on how you recommend performing updates to modify configuration of an already deployed instance.

### Expected Behavior

Configuration changes can be made to the helm chart values can be applied and the server runs with the new configuration or infrastructure.

### Steps To Reproduce

1. Deploy this helm chart into a k8s cluster.
2. Update or add a value to the helm chart (e.g. Add a value to `.Values.configuration.properties`)
3. Attempt to update the helm chart.

Error:
Helm upgrade failed for release graphdb/graphdb-graphdb-helm with chart graphdb@11.2.2: cannot patch "graphdb-graphdb-helm" with kind StatefulSet: StatefulSet.apps "graphdb-graphdb-helm" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden

**Comment by mihailradkov** [comment]
Hey @JaredDarling, 

What are you trying to update in the StatefulSet? As you have encountered, not everything can be updated once a StatefulSet is created. This is by design, and all Kubernetes vendors enforce this to prevent disruptions to stateful applications.

GraphDB is a stateful application that persists data on the filesystem so the usage of a StatefulSet is critical due to the following:
* Each pod has a stable identified hence a stable network address which is crucial for using a GraphDB HA cluster.
* Each pod receives a dedicated PV/PVC via the PVC templates. This is not possible with a Deployment.
* Updates to pods are ordered and predictable

I hope this makes things clearer.
